### ISSUE TITLE
Error: Invalid expression. The property <Id> is not defined on a target type 

### ISSUE THREAD

**Issue by eMTeTeam** [mikependon/RepoDB#364] opened 2020-01-03 16:07 UTC
I have an Interface with base fields
```
public interface IWithId
    {
        /// <summary>
        /// Gets or sets the primary id.
        /// </summary>
        string Id { get; set; }
    }
```

Inherited class: 
```
[Map("ACCOUNTS")]
public class Account : IWithId
    {
        /// <summary>
        /// Gets or sets the account primary id.
        /// </summary>
        [Map("AccountID")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the account name.
        /// </summary>
        [Map("AccountName")]
        public string Name { get; set; }
    }

```
I have a Generic Repository class. Currently I'm trying to get the Account information By Id using below code,
```
public abstract class RepositoryBase<TModel> : where TModel : class, IWithId, new()
{

public async Task<TModel> ReadByIdAsync(string id, CancellationToken token)
        {
            var model = await QueryAsync(entity => entity.Id == id);
            return model.FirstOrDefault();
        }
}
```
In above I’m getting this error 

_`RepoDb.Exceptions.InvalidExpressionException: 'Invalid expression '(entity.Id == value(eMTe.Expense.Repository.Implementation.RepositoryBase1+<>c__DisplayClass7_0[eMTe.Expense.Model.Account]).id)'. The property Id is not defined on a target type 'eMTe.Expense.Model.Account'.'`_

Expectation is Id should be resolved to get the Account class information and ‘_AccountID_’ should be added in where class. But the Expression field is resolving as _IWithId_ Interface and no Map attribute is resolved.
This is the reason for this error.

I did some analysis and issue is happening in below code

```
public class QueryField

var field = expression.GetField();
            if (PropertyCache.Get<TEntity>().Any(property => string.Equals(PropertyMappedNameCache.Get(property.PropertyInfo), field.Name, StringComparison.OrdinalIgnoreCase)) == false)
            {
                throw new InvalidExpressionException($"Invalid expression '{expression.ToString()}'. The property {field.Name} is not defined on a target type '{typeof(TEntity).FullName}'.");
            }
```
Line No: 212
The `_expression.GetField();_` method returns ‘_Id_’ but not ‘_AccountID_’

This stackoverflow talks about Get overridden property attribute and the exact scenario I’m facing.
https://stackoverflow.com/questions/20835132/get-overridden-property-attribute

Please suggest a solution for this.

**Comment by mikependon** [comment] 2020-01-03 22:29
Currently testing with a simplistic approach.

**Database Codes:**

```
CREATE TABLE IF NOT EXISTS `Accounts`
(
	`AccountId` nvarchar(32) NOT NULL,
	`AccountName` nvarchar(256) NOT NULL
)
ENGINE = InnoDB;
```

**Insert Records.**

```
insert into `Accounts` (`AccountId`, `AccountName`) values ('WhatEver', 'WhatEver');
insert into `Accounts` (`AccountId`, `AccountName`) values ('AccountId', 'AccountName');
```

**Test Codes:**

```csharp
using Microsoft.VisualStudio.TestTools.UnitTesting;
using MySql.Data.MySqlClient;
using RepoDb.Attributes;
using System.Linq;

namespace RepoDb.MySql.IntegrationTests
{
    public interface IWithId
    {
        /// <summary>
        /// Gets or sets the primary id.
        /// </summary>
        string Id { get; set; }
    }

    [Map("ACCOUNTS")]
    public class Account : IWithId
    {
        /// <summary>
        /// Gets or sets the account primary id.
        /// </summary>
        [Map("AccountID")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the account name.
        /// </summary>
        [Map("AccountName")]
        public string Name { get; set; }
    }

    public class AccountRepository : BaseRepository<Account, MySqlConnection>
    {
        public AccountRepository(string connectionString)
            : base(connectionString)
        { }
    }

    [TestClass]
    public class ReportedTests
    {
        [TestInitialize]
        public void Initialize()
        {
            MySqlBootstrap.Initialize();
        }

        private string ConnectionString => @"Server=localhost;Database=RepoDb;Uid=user;Pwd=Password123;";

        [TestMethod]
        public void TestConnectionQueryGroupParse()
        {
            var queryGroup = QueryGroup.Parse<Account>(e => e.Id == "WhatEver");
            Assert.AreEqual(1, queryGroup.GetFields(true).Count());
        }

        [TestMethod]
        public void TestConnectionQueryAsync()
        {
            using (var connection = new MySqlConnection(ConnectionString))
            {
                var results = connection.QueryAsync<Account>(e => e.Id == "WhatEver").Result;
                Assert.AreEqual(1, results.Count());
            }
        }

        [TestMethod]
        public void TestConnectionQueryAllAsync()
        {
            using (var connection = new MySqlConnection(ConnectionString))
            {
                var results = connection.QueryAllAsync<Account>().Result;
                Assert.IsTrue(results.Count() > 0);
            }
        }

        [TestMethod]
        public void TestAccountRepositoryQueryAsync()
        {
            using (var repository = new AccountRepository(ConnectionString))
            {
                var results = repository.QueryAsync(e => e.Id == "WhatEver").Result;
                Assert.AreEqual(1, results.Count());
            }
        }

        [TestMethod]
        public void TestAccountRepositoryQueryAllAsync()
        {
            using (var repository = new AccountRepository(ConnectionString))
            {
                var results = repository.QueryAllAsync().Result;
                Assert.IsTrue(results.Count() > 0);
            }
        }
    }
}

```

**Comment by mikependon** [comment] 2020-01-03 23:02
My codes above were working. Would you be able to check it? I used the version *RepoDb.MySql (v1.0.2)*.

In addition, here is what I can get based from your report. I am getting the correct mappings for *Id* property into *AccountID* column.

![image](https://user-images.githubusercontent.com/591015/71754125-3997d000-2e85-11ea-9a1e-02ae9e327682.png)

**Comment by mikependon** [comment] 2020-01-03 23:06
I am doing this at the lower-level implementation. If the [Map] attribute is not resolved, then it will use the property name instead.

![image](https://user-images.githubusercontent.com/591015/71754332-fb4ee080-2e85-11ea-861b-72b88e39bf6b.png)

Link: https://github.com/mikependon/RepoDb/blob/8226aa3670a6f71d6ea3f9218c572bec459b2708/RepoDb.Core/RepoDb/Extensions/PropertyInfoExtension.cs#L84

**Comment by mikependon** [comment] 2020-01-03 23:19
**For me to be able to proceed further, please do this. I will try my luck to replicate it.**
- Share the actual Table Schema
- Share the actual code of the Repository who inherits the RepositoryBase

 Again, this works on my end. But, a workaround fix for you is any if the following:
- Use *QueryField* instead of *Linq Expression*.
```csharp
Query<Account>(new QueryField(“Id”, id));
```
- Use a *dynamic* expression instead.
```csharp
Query<Account>(new { Id = id });
```
Note: You are not maximizing the compiler’s AOT compilation.
- Rename the property *Id* to *AccountId*.

**Comment by eMTeTeam** [comment] 2020-01-04 10:08
**My code flow**
```
    public interface IWithId
    {
        string Id { get; set; }
    }

    [Map("ACCOUNTS")]
    public class Account : IWithId
    {
        [Map("AccountID")]
        public string Id { get; set; }

        [Map("AccountName")]
        public string Name { get; set; }
    }

**Starting Point:**

    public class AccountBusinessLayer : BaseCrudBL<Account>
    {
        public async Task<AccountDetailsDTO> ReadAccountById(string id, CancellationToken token)
        {
            var account = await ReadByIdAsync(id, token);
            return account.To<AccountDetailsDTO>();
        }
    }



**BaseCRUD operation Class**

    public interface IBaseCrudBL<TModel> where TModel : class
    {
        Task<TModel> ReadByIdAsync(string id, CancellationToken token);
    }

    public class BaseCrudBL<TModel> : IBaseCrudBL<TModel> where TModel : class, IWithId
    {
        private readonly IRepository<TModel> _repository;
        public BaseCrudBL(IRepository<TModel> repository)
        {
            _repository = repository;
        }

        public Task<TModel> ReadByIdAsync(string id, CancellationToken token)
        {
            return _repository.ReadByIdAsync(id, token);
        }
    }



**Repository Class to connect with Database with RepoDB:**

    public interface IRepository<TModel> where TModel : class
    {
        Task<TModel> ReadByIdAsync(string id, CancellationToken token);
    }

    public abstract class RepositoryBase<TModel> : BaseRepository<TModel, MySqlConnection>, Repository<TModel> where TModel : class, IWithId, new()
    {
        public async Task<TModel> ReadByIdAsync(string id, CancellationToken token)
        {
            var model = await QueryAsync(entity => entity.Id == id);
            return model.FirstOrDefault();
        }
    }
```

**Comment by eMTeTeam** [comment] 2020-01-04 10:14
In above code -> 
1. **AccountBusinessLayer** is the starting point and this class only knows about '**Account**' model 
class

2. **ReadAccountById** method calls the **BaseCrudBL** class and gets the generic Model type **TModel** and it doesn;t know about **Account** Model Class

3. **ReadByIdAsync** method calls the Repository class **RepositoryBase** and it also gets the generic model type **TModel** of type **IWithId**

4. `var model = await QueryAsync(entity => entity.Id == id);` in this line entity.id is present inside **IWithId** interface. While resolving this id field inside RepoDb it knows only about **IWithId** Interface but not about **Account** model class.
This is the reason for the error.

**Comment by eMTeTeam** [comment] 2020-01-04 10:17
> Currently testing with a simplistic approach.
> 
> **Database Codes:**
> 
> ```
> CREATE TABLE IF NOT EXISTS `Accounts`
> (
> 	`AccountId` nvarchar(32) NOT NULL,
> 	`AccountName` nvarchar(256) NOT NULL
> )
> ENGINE = InnoDB;
> ```
> 
> **Insert Records.**
> 
> ```
> insert into `Accounts` (`AccountId`, `AccountName`) values ('WhatEver', 'WhatEver');
> insert into `Accounts` (`AccountId`, `AccountName`) values ('AccountId', 'AccountName');
> ```
> 
> **Test Codes:**
> 
> ```cs
> using Microsoft.VisualStudio.TestTools.UnitTesting;
> using MySql.Data.MySqlClient;
> using RepoDb.Attributes;
> using System.Linq;
> 
> namespace RepoDb.MySql.IntegrationTests
> {
>     public interface IWithId
>     {
>         /// <summary>
>         /// Gets or sets the primary id.
>         /// </summary>
>         string Id { get; set; }
>     }
> 
>     [Map("ACCOUNTS")]
>     public class Account : IWithId
>     {
>         /// <summary>
>         /// Gets or sets the account primary id.
>         /// </summary>
>         [Map("AccountID")]
>         public string Id { get; set; }
> 
>         /// <summary>
>         /// Gets or sets the account name.
>         /// </summary>
>         [Map("AccountName")]
>         public string Name { get; set; }
>     }
> 
>     public class AccountRepository : BaseRepository<Account, MySqlConnection>
>     {
>         public AccountRepository(string connectionString)
>             : base(connectionString)
>         { }
>     }
> 
>     [TestClass]
>     public class ReportedTests
>     {
>         [TestInitialize]
>         public void Initialize()
>         {
>             MySqlBootstrap.Initialize();
>         }
> 
>         private string ConnectionString => @"Server=localhost;Database=RepoDb;Uid=user;Pwd=Password123;";
> 
>         [TestMethod]
>         public void TestConnectionQueryGroupParse()
>         {
>             var queryGroup = QueryGroup.Parse<Account>(e => e.Id == "WhatEver");
>             Assert.AreEqual(1, queryGroup.GetFields(true).Count());
>         }
> 
>         [TestMethod]
>         public void TestConnectionQueryAsync()
>         {
>             using (var connection = new MySqlConnection(ConnectionString))
>             {
>                 var results = connection.QueryAsync<Account>(e => e.Id == "WhatEver").Result;
>                 Assert.AreEqual(1, results.Count());
>             }
>         }
> 
>         [TestMethod]
>         public void TestConnectionQueryAllAsync()
>         {
>             using (var connection = new MySqlConnection(ConnectionString))
>             {
>                 var results = connection.QueryAllAsync<Account>().Result;
>                 Assert.IsTrue(results.Count() > 0);
>             }
>         }
> 
>         [TestMethod]
>         public void TestAccountRepositoryQueryAsync()
>         {
>             using (var repository = new AccountRepository(ConnectionString))
>             {
>                 var results = repository.QueryAsync(e => e.Id == "WhatEver").Result;
>                 Assert.AreEqual(1, results.Count());
>             }
>         }
> 
>         [TestMethod]
>         public void TestAccountRepositoryQueryAllAsync()
>         {
>             using (var repository = new AccountRepository(ConnectionString))
>             {
>                 var results = repository.QueryAllAsync().Result;
>                 Assert.IsTrue(results.Count() > 0);
>             }
>         }
>     }
> }
> ```

In your code, can you make change to `BaseRepository<TModel, MySqlConnection>` and pass the **Account** model reference as **TModel** like this `var repository = new AccountRepository<Account>(ConnectionString)` then I believe you will get this error.

**Comment by mikependon** [comment] 2020-01-04 10:25
Okay, I will try that later. Thanks

**Comment by mikependon** [comment] 2020-01-04 12:25
After following your advice, this code seems to be working fine. I cannot replicate your issue!

```csharp
using Microsoft.VisualStudio.TestTools.UnitTesting;
using MySql.Data.MySqlClient;
using RepoDb.Attributes;
using System.Linq;

namespace RepoDb.MySql.IntegrationTests
{
    public interface IWithId
    {
        /// <summary>
        /// Gets or sets the primary id.
        /// </summary>
        string Id { get; set; }
    }

    [Map("ACCOUNTS")]
    public class Account : IWithId
    {
        /// <summary>
        /// Gets or sets the account primary id.
        /// </summary>
        [Map("AccountID")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the account name.
        /// </summary>
        [Map("AccountName")]
        public string Name { get; set; }
    }

    public class GenericRepository<TModel> : BaseRepository<TModel, MySqlConnection>
        where TModel : class
    {
        public GenericRepository(string connectionString)
            : base(connectionString)
        { }
    }

    [TestClass]
    public class ReportedTests
    {
        [TestInitialize]
        public void Initialize()
        {
            MySqlBootstrap.Initialize();
        }

        private string ConnectionString => @"Server=localhost;Database=RepoDb;Uid=user;Pwd=Password123;";

        [TestMethod]
        public void TestConnectionQueryGroupParse()
        {
            var queryGroup = QueryGroup.Parse<Account>(e => e.Id == "WhatEver");
            Assert.AreEqual(1, queryGroup.GetFields(true).Count());
        }

        [TestMethod]
        public void TestConnectionQueryAsync()
        {
            using (var connection = new MySqlConnection(ConnectionString))
            {
                var results = connection.QueryAsync<Account>(e => e.Id == "WhatEver").Result;
                Assert.AreEqual(1, results.Count());
            }
        }

        [TestMethod]
        public void TestConnectionQueryAllAsync()
        {
            using (var connection = new MySqlConnection(ConnectionString))
            {
                var results = connection.QueryAllAsync<Account>().Result;
                Assert.IsTrue(results.Count() > 0);
            }
        }

        [TestMethod]
        public void TestAccountRepositoryQueryAsync()
        {
            using (var repository = new GenericRepository<Account>(ConnectionString))
            {
                var results = repository.QueryAsync(e => e.Id == "WhatEver").Result;
                Assert.AreEqual(1, results.Count());
            }
        }

        [TestMethod]
        public void TestAccountRepositoryQueryAllAsync()
        {
            using (var repository = new GenericRepository<Account>(ConnectionString))
            {
                var results = repository.QueryAllAsync().Result;
                Assert.IsTrue(results.Count() > 0);
            }
        }
    }
}
```

I will try mimicking what 's your actual implementation.

**Comment by mikependon** [comment] 2020-01-04 12:37
Replicated it now, after tweaking to these codes.

```csharp
using Microsoft.VisualStudio.TestTools.UnitTesting;
using MySql.Data.MySqlClient;
using RepoDb.Attributes;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace RepoDb.MySql.IntegrationTests
{
    public interface IWithId
    {
        /// <summary>
        /// Gets or sets the primary id.
        /// </summary>
        string Id { get; set; }
    }

    [Map("ACCOUNTS")]
    public class Account : IWithId
    {
        /// <summary>
        /// Gets or sets the account primary id.
        /// </summary>
        [Map("AccountID")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the account name.
        /// </summary>
        [Map("AccountName")]
        public string Name { get; set; }
    }

    public interface IRepository<TModel> where TModel : class
    {
        Task<TModel> ReadByIdAsync(string id, CancellationToken token);
    }

    public abstract class RepositoryBase<TModel> : BaseRepository<TModel, MySqlConnection>,
        IRepository<TModel>
        where TModel : class, IWithId, new()
    {
        public RepositoryBase()
            : base(@"Server=localhost;Database=RepoDb;Uid=user;Pwd=Password123;")
        { }

        public async Task<TModel> ReadByIdAsync(string id, CancellationToken token)
        {
            var model = await QueryAsync(entity => entity.Id == id);
            return model.FirstOrDefault();
        }
    }

    public class GenericRepository<TModel> : RepositoryBase<TModel>
        where TModel : class, IWithId, new()
    {
    }


    public interface IBaseCrudBL<TModel> where TModel : class
    {
        Task<TModel> ReadByIdAsync(string id, CancellationToken token);
    }

    public class BaseCrudBL<TModel> : IBaseCrudBL<TModel>
        where TModel : class, IWithId
    {
        private readonly IRepository<TModel> _repository;

        public BaseCrudBL(IRepository<TModel> repository)
        {
            _repository = repository;
        }

        public Task<TModel> ReadByIdAsync(string id, CancellationToken token)
        {
            return _repository.ReadByIdAsync(id, token);
        }
    }

    public class AccountBusinessLayer : BaseCrudBL<Account>
    {
        public AccountBusinessLayer()
            : base(new GenericRepository<Account>())
        { }

        public async Task<Account> ReadAccountById(string id, CancellationToken token)
        {
            var account = await ReadByIdAsync(id, token);
            return account;
        }
    }


    [TestClass]
    public class ReportedTests
    {
        [TestInitialize]
        public void Initialize()
        {
            MySqlBootstrap.Initialize();
        }

        [TestMethod]
        public void TestAccountBusinessLayerCall()
        {
            var repository = new AccountBusinessLayer();
            var entity = repository.ReadAccountById("WhatEver", CancellationToken.None).Result;
            Assert.IsNotNull(entity);
        }
    }
}
```
**Exception:**

![image](https://user-images.githubusercontent.com/591015/71765611-5ec52680-2ef7-11ea-9aa6-06dbdd7a28f8.png)

**Comment by eMTeTeam** [comment] 2020-01-04 13:29
Thank you for your effort on looking at this.
This is the exact issue that I'm facing. 
What is the refactoring required to make this work? 
The problem is that **entity.Id** is of type **IWithId** and it doesn't have Map Attribute.  
The code in RepoDb **expression.GetField()** doesn't resolve the property name from **TEntity** but from it's original member information.
Can we type caste the expression field from TEntity?
Example: https://stackoverflow.com/questions/20835132/get-overridden-property-attribute

**Comment by mikependon** [comment] 2020-01-04 13:31
I will issue a fix for this. It is beyond your control as a consumer. It should be handled within RepoDb. I will do issue a beta for next version for you. Currently, I am running all Integration Tests.

Btw, it is a core change for the Expression Trees - so I need to revalidate all test-cases are passing before issuing a new version. I am almost done!

**Comment by eMTeTeam** [comment] 2020-01-04 13:33
Thank you so much! 👍

**Comment by mikependon** [comment] 2020-01-04 14:29
This issue is now working on the end-user. Confirmed through message below.

![image](https://user-images.githubusercontent.com/591015/71767005-f8480480-2f06-11ea-93af-fbff30ed582b.png)

**Comment by mikependon** [comment] 2020-01-19 20:56
Just deployed the v1.0.3.

**Closed as completed by mikependon** 2020-01-19 20:56 UTC
Labels: bug, todo, priority, deployed, fixed
