### ISSUE TITLE
Possible bug - Enum with Flag attribute is not correctly handled

### ISSUE THREAD

**Issue by lucwuyts** [mikependon/RepoDB#624] opened 2020-10-21 11:07 UTC
The library does not handle Enums with the Flag attribute correctly.

I tried  to solve this with an PropertyHandler, but when more than 1 flag is set, the input field in the Get function is null.
So the original enum is not passed to this function

**Comment by mikependon** [comment] 2020-10-21 11:09
@lucwuyts - though I understand this problem, can you also specify some code to provide more context? Thanks

**Comment by lucwuyts** [comment] 2020-10-21 11:46
Consider this enum:

```
	[Flags]
	public enum Functie
	{
		Geen = 0x0000,
		
		Voorzitter = 0x0001,
		Secretaris = 0x0002,
		Penningmeester = 0x0004,

        Inst_Heli = 0x0008,
		Inst_Vliegtuig = 0x0010,
		
		Exam_Heli = 0x0020,
		Exam_Vliegtuig = 0x0040,
		
		Onderhoud_Veld = 0x0080,

        TerreinVerantwoordelijke = 0x0100,
		
        Vrijwilliger = 0x0200,

        VeiligheidsPiloot = 0x0400,

        OnderVoorzitter = 0x0800,        
}
```

When Functie has multiple flags, ToString() shows them concatenated with komma as separator.

Like this:

`"Inst_Heli, Inst_Vliegtuig, Onderhoud_Veld, OnderVoorzitter"`

I tried using this PropertyHandler:

``` public class FunctiePropertyHandler : IPropertyHandler<Functie, string>
    {
        public string Get(Functie input, ClassProperty property)
        {
            //Console.WriteLine($"Get {input}");
            return input.ToString();
        }

        public Functie Set(string input, ClassProperty property)
        {
            //Console.WriteLine($"Set {input}");
            var retval = Functie.Geen;
            if (!string.IsNullOrWhiteSpace(input))
            {
                var stukken = input.Split('|');
                foreach (var stuk in stukken)
                {
                    var deelFunctie = (Functie)Enum.Parse(typeof(Functie), stuk);
                    retval |= deelFunctie;
                }
            }
            return retval;
        }
    }
```

In the Set function, the string "input" is null when there is more than 1 option set.

**Comment by lucwuyts** [comment] 2020-10-22 10:49
Because the library doesn't work, i thought the parsing of such flag enum has to be done part per part, but this is not thrue.
Just this would suffice:

`return Enum.Parse(typeof(Functie), input)`

so above Set function is much too complicated, sorry about that.  But the problem remains off course.

**Comment by mikependon** [comment] 2020-10-27 12:06
Upon further investigation, the `Enum.GetName()` method is failing to retrieved the value of the Enum if the `Flags` attribute is present.

```csharp
[Flags]
public enum StorageType
{
    File = 1,
    Folder = 2,
    Directory = 4,
    Drive = 8,
    InternalStorage = 16,
    MemoryStorage = 32
}
```

And this one is always returning `NULL` as what RepoDB does.

![image](https://user-images.githubusercontent.com/591015/97299466-45f67a80-1855-11eb-91c4-e6af2955429c.png)

**Comment by mikependon** [comment] 2020-10-28 14:51
This is now deployed at [RepoDB v1.12.5-beta1](https://www.nuget.org/packages/RepoDb/1.12.5-beta1). Can you upgrade and test it there? Thanks

**Comment by mikependon** [comment] 2020-11-03 19:24
Closing this ticket now. Please do not hesitate to reopen or contact us ASAP if the issue is not fixed on your end.

**Closed as completed by mikependon** 2020-11-03 19:24 UTC
Labels: bug, todo, deployed, fixed, pre-discussed
