### ISSUE TITLE
Bug: Regression Issue

### ISSUE THREAD

**Issue by sellig** [mikependon/RepoDB#457] opened 2020-06-20 07:15 UTC
Hello Michael,

So currently, I'm using
RepoDb  v1.11.0
RepoDbSqlServer v1.0.7

I'm having my domain entities deriving from this base class

```csharp
   [Serializable]
    public abstract class Entity<T> : IEquatable<T>
    {
          protected Entity()
        {
            Id = long.MinValue;
            Key = Guid.NewGuid();
            Visibility = Visibilities.Visible;
            DateCreation = new DateTime();
        }

        public long Id { get; set; }

         public Guid Key { get; set; }

        public bool IsNew => (Id == long.MinValue);

        public Visibilities Visibility { get; set; }
        
        public DateTime DateCreation { get; set; }

        public DateTime DateModification { get; set; }

        public int CreatorId { get; set; }

        public int ModifierId { get; set; }

        public bool Equals(Entity<T> other)
        {
            if (other is null)
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            if (this.GetType() != other.GetType())
            {
                return false;
            }

            bool otherIsTransient = Equals(other.Key, Guid.Empty);
            bool thisIsTransient = Equals(Key, Guid.Empty);

            if (otherIsTransient && thisIsTransient)
            {
                return ReferenceEquals(other, this);
            }

            return other.Key.Equals(Key);
        }

        public override bool Equals(object other) => other is Entity<T> entity && Equals(entity);

        public bool Equals([AllowNull] T other)
        {
            if (other == null)
            {
                return false;
            }

            return this.Equals(other);
        }

        public static bool operator ==(Entity<T> a, Entity<T> b)
        {
            if (a is null && b is null)
            {
                return true;
            }

            if (a is null || b is null)
            {
                return false;
            }

            return a.Equals(b);
        }

        public static bool operator !=(Entity<T> a, Entity<T> b)
        {
            return !(a == b);
        }

        public override int GetHashCode() => (Id, Key).GetHashCode();
    }
```
Example 
```csharp
    [Serializable]
    public sealed class Participant : Entity<Participant>
    {

        public string Email { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }
    }
```
With my current version of RepoDb v1.11.0, v1.0.7  I'm using, Insert<Participant>(participant...) or Update<Participant>(participant...) is working but If I switch to the latest version of RepoDb v1.11.3 and v.1.0.11-beta1 I have this error

```csharp
{"Object reference not set to an instance of an object."}
at RepoDb.Extensions.PropertyInfoExtension.GetHandledValue(PropertyInfo property, Object entity, Type declaringType)
   at RepoDb.Extensions.PropertyInfoExtension.GetHandledValue(PropertyInfo property, Object entity)
   at RepoDb.Extensions.PropertyInfoExtension.AsQueryField(PropertyInfo property, Object entity, Boolean appendUnderscore)
   at RepoDb.Extensions.PropertyInfoExtension.AsQueryField(PropertyInfo property, Object entity)
   at RepoDb.DbConnectionExtension.ToQueryGroup[TEntity](ClassProperty property, TEntity entity)
   at RepoDb.DbConnectionExtension.Update[TEntity](IDbConnection connection, TEntity entity, String hints, Nullable`1 commandTimeout, IDbTransaction transaction, ITrace trace, IStatementBuilder statementBuilder)
   at repository.Save(Participant participant) in **********\Repository.cs:line 35
```
Best

Gilles

**Comment by mikependon** [comment] 2020-06-20 08:22
This is a newly introduced for PropertyHandler handling PR towards this library. I will issue a fix for you ASAP.

**Comment by mikependon** [comment] 2020-06-20 14:09
I could not replicate the issue of yours TBH. However, I had added a thorough (whole file) and targeted Integration Tests for Inheritance which can be found [here](https://github.com/mikependon/RepoDb/blob/master/RepoDb.Core/RepoDb.Tests/RepoDb.IntegrationTests/InheritanceTest.cs). It uses this [model](https://github.com/mikependon/RepoDb/blob/master/RepoDb.Core/RepoDb.Tests/RepoDb.IntegrationTests/Models/InheritedIdentityTable.cs) during the test.

Also, I added some null checks on the code that could possibly being triggered by your case. The changes can be found from this [method](https://github.com/mikependon/RepoDb/blob/f2de6a6665e87c54167a66621ccd96393b38e68d/RepoDb.Core/RepoDb/Extensions/PropertyInfoExtension.cs#L286).

A new beta for has been released, can you please check/test it for me by simply upgrading to [RepoDb v1.11.4-beta1](https://www.nuget.org/packages/RepoDb/1.11.4-beta1)?

**Comment by sellig** [comment] 2020-06-20 18:02
Thank you.
I have tested and still have the same issue.
I think it's coming from my Inheritance which is more 'complicated' than yours as it is using generic
```csharp
    public sealed class Participant : Entity<Participant>
```

**Comment by mikependon** [comment] 2020-06-20 18:18
Thank you for testing, I will mimic the complexity of your inherittance to simulate such issues.

**Comment by mikependon** [comment] 2020-06-20 18:34
Seems the issue is [here](https://github.com/mikependon/RepoDb/blob/f2de6a6665e87c54167a66621ccd96393b38e68d/RepoDb.Core/RepoDb/Extensions/PropertyInfoExtension.cs#L291). I am afraid to put a null checks as the issue seems to be really a missing property. Would you be able to share more context when calling the 'Update' method? I mean, is it only an instance of 'Participant' are you passing in the method (and nothing else)?

**Comment by mikependon** [comment] 2020-06-21 04:29
I had replicated your issue using your inheritance structure. Thanks for pushing this one back.

**Comment by mikependon** [comment] 2020-06-21 05:00
The fix is now available at [RepoDb v1.11.4-beta2](https://www.nuget.org/packages/RepoDb/1.11.4-beta2). It is still covered by the same list of [Integration Tests](https://github.com/mikependon/RepoDb/blob/master/RepoDb.Core/RepoDb.Tests/RepoDb.IntegrationTests/InheritanceTest.cs) that I introduced recently, but with the same inheritance structure as yours within the [model](https://github.com/mikependon/RepoDb/blob/master/RepoDb.Core/RepoDb.Tests/RepoDb.IntegrationTests/Models/InheritedIdentityTable.cs). Please test and revert if you still have questions. I hope that 2 of your issues is now addressed by this.

**Comment by sellig** [comment] 2020-06-26 12:05
Thank you very much Michael, been busy this day and have no time to follow.
I will make a try and give you my feedback.

Best

gilles

**Comment by mikependon** [comment] 2020-06-26 12:44
@sellig - no worries. Feel free to revert anytime if you still encounter the problems.

**Comment by sellig** [comment] 2020-06-26 20:00
I have tested my code with the last version and all is fine. 
You can close the ticket.
Thank you for your support.

Gilles

**Closed as completed** 2020-06-27 06:34 UTC
Labels: bug, todo, deployed, help wanted, refactoring
